### ISSUE TITLE
Invalid directory /Volumes/node_modules/Dimensions

### ISSUE THREAD

**Issue by fbi080703** [leecade/react-native-swiper#67]
bcoiueufrgwzffebbarleytkoipx/Build/Products/Debug-iphonesimulator/AwesomeProject.app/main.jsbundle --assets-dest /Users/Apple/Library/Developer/Xcode/DerivedData/AwesomeProject-bcoiueufrgwzffebbarleytkoipx/Build/Products/Debug-iphonesimulator/AwesomeProject.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module Dimensions from /Volumes/DataSource/reactnative/AwesomeProject/node_modules/react-native-swiper/dist/index.js: Invalid directory /Volumes/node_modules/Dimensions
    at ResolutionRequest.js:351:15
    at tryCallOne (/Volumes/DataSource/reactnative/AwesomeProject/node_modules/promise/lib/core.js:37:12)
    at /Volumes/DataSource/reactnative/AwesomeProject/node_modules/promise/lib/core.js:103:15
    at flush (/Volumes/DataSource/reactnative/AwesomeProject/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
See logs /var/folders/jt/gyd40qnn3gz6rc1dptzjqyfm0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Volumes/DataSource/reactnative/AwesomeProject/node_modules/bser/index.js:289:10)
    at /Volumes/DataSource/reactnative/AwesomeProject/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
Command /bin/sh failed with exit code 1

**Comment by alubling** [comment]
Had the same issue with Dimensions. Check out my comment at the end of this thread:

https://github.com/facebook/react-native/issues/3817

**Comment by leecade** [comment]
fixed `v1.4.0` thanks @alubling
