### ISSUE TITLE
OutOfMemoryError when there are a lot of <Image/> in the slides

### ISSUE THREAD

**Issue by JiboStore** [leecade/react-native-swiper#730]
### Which OS ?
Android

### Version
Which versions are you using:
1.5.13

- react-native-swiper v?
- react-native v0.47.2

### Expected behaviour
Using this code, just modify `imgList` to contain a lot of jpeg files located in the device's external storage (SD Card). It is expected to load through 'til the end of the list
https://github.com/leecade/react-native-swiper/blob/master/examples/components/LoadMinimal/index.js

### Actual behaviour
After a few images (around 20+), the app crashed.
Logcat shows this error:
E/art     (23532): Throwing OutOfMemoryError "Failed to allocate a 4041612 byte allocation with 3855344 free bytes and 3MB until OOM"
E/AndroidRuntime(23532): FATAL EXCEPTION: Thread-1654
E/AndroidRuntime(23532): Process: com.example.app, PID: 23532
E/AndroidRuntime(23532): java.lang.OutOfMemoryError: Failed to allocate a 4041612 byte allocation with 3855344 free bytes and 3MB until OOM
E/AndroidRuntime(23532): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(23532): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(23532): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
E/AndroidRuntime(23532): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
E/AndroidRuntime(23532): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:183)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:63)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
E/AndroidRuntime(23532): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(23532): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(23532): 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
E/AndroidRuntime(23532): 	at java.lang.Thread.run(Thread.java:818)

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
- just add a lot more entries to `imgList` in the specified example

### Steps to reproduce
1. scroll
2. scroll 'til it crashed
3.

**Comment by JiboStore** [comment]
I didn't know of loadMinimal before, I was using as normal (without the loadMinimal) until suddenly the scrolling shows no more image, thus I browse for other options and found the loadMinimal sample. Tried it out and the OOM happens. It happens around 25+ scrolls out of 70+ images. Previously (without the loadMinimal), image went blank at around 25+ scrolls too... I wonder if these are related

**Comment by machester4** [comment]
[https://github.com/leecade/react-native-swiper/issues/547](url) 
if this happens, in this link I talked about that with my other github account. the problem is that when loading all local images can not be cached as would be done from a url. I can recommend something that is not the solution but it can help you in something, is to create two arrays one with the local images and the second with the components that you want to show in the swiper, the images of the components will be loaded dynamically as the index of the swiper changes. using the index you will have to obtain the image of the array of images. that will make all the components have the same image and in this way only one image will be cached at a time. This is not the best solution but you can go playing with this idea and get a good result I've done it a while ago and it worked out well.
