### ISSUE TITLE
crash on android in release mode

### ISSUE THREAD

**Issue by takunee** [leecade/react-native-swiper#891]
### Version
Which versions are you using:

- react-native-swiper v1.5.13
- react-native v0.5.7

=================================

> com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'left' in shadow node of type: RCTView
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:157)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:61)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:458)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:295)

**Comment by allindeveloper** [comment]
I'm currently experiencing this issue, any solution yet ?

**Comment by allindeveloper** [comment]
i was using react-native-svg to render svgs on each `<View/>` insider `<Swiper/>`
this solved my issue
https://github.com/react-native-svg/react-native-svg#problems-with-proguard
